// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SistemaRegulacao.Models
{
    [Table("log")]
    public partial class Log
    {
        [Key]
        public long Id { get; set; }
        [Column("log_date", TypeName = "datetime")]
        public DateTime LogDate { get; set; }
        [Column("id_user")]
        public long IdUser { get; set; }
        [Column("text")]
        public string Text { get; set; }

        [ForeignKey("IdUser")]
        [InverseProperty("Logs")]
        public virtual User IdUserNavigation { get; set; }
    }
}