// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SistemaRegulacao.Models
{
    [Table("users")]
    public partial class User
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("user")]
        [StringLength(100)]
        [Unicode(false)]
        public string User1 { get; set; }
        [Required]
        [Column("email")]
        [StringLength(100)]
        [Unicode(false)]
        public string Email { get; set; }
        [Required]
        [Column("password")]
        [StringLength(100)]
        [Unicode(false)]
        public string Password { get; set; }
        [Column("created_at", TypeName = "datetime")]
        public DateTime CreatedAt { get; set; }
        [Column("deleted_at", TypeName = "datetime")]
        public DateTime? DeletedAt { get; set; }
        [Column("deleted_by")]
        [StringLength(100)]
        [Unicode(false)]
        public string DeletedBy { get; set; }
        [Column("active")]
        public bool? Active { get; set; }
    }
}