// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SistemaRegulacao.Models
{
    [Table("users")]
    public partial class User
    {
        public User()
        {
            Logs = new HashSet<Log>();
        }

        [Required]
        [Column("name")]
        [StringLength(100)]
        [Unicode(false)]
        public string Name { get; set; }
        [Required]
        [Column("email")]
        [StringLength(100)]
        [Unicode(false)]
        public string Email { get; set; }
        [Required]
        [Column("password")]
        [StringLength(100)]
        [Unicode(false)]
        public string Password { get; set; }
        [Column("created_at", TypeName = "datetime")]
        public DateTime CreatedAt { get; set; }
        [Column("deleted_at", TypeName = "datetime")]
        public DateTime? DeletedAt { get; set; }
        [Column("deleted_by")]
        [StringLength(100)]
        [Unicode(false)]
        public string DeletedBy { get; set; }
        [Column("active")]
        public bool? Active { get; set; }
        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Column("role")]
        public long Role { get; set; }
        [Required]
        [Column("cpf")]
        [StringLength(11)]
        public string Cpf { get; set; }

        [ForeignKey("Role")]
        [InverseProperty("Users")]
        public virtual Role RoleNavigation { get; set; }
        [InverseProperty("IdUserNavigation")]
        public virtual ICollection<Log> Logs { get; set; }
    }
}